### ISSUE TITLE
How to use multiple cores?

### ISSUE THREAD

**Issue by dnl4** [juanmrad/docker-unused-scanner#4]
I'm trying to run this image using all 8 cores from my MAC. But its seems like it is never using it at all

How can I use all cores?

![image](https://user-images.githubusercontent.com/23690346/115972792-dec93280-a526-11eb-8e44-f911624e58d9.png)

![image](https://user-images.githubusercontent.com/23690346/115972814-0ddfa400-a527-11eb-8ac7-2b49faa9c486.png)

**Comment by juanmrad** [comment]
@dnl4 This will be something that the package needs to support in order to take advantage of multiple cores or parallelism
